spring:
  application:
    name: myapigateway
  config:
    import: optional:file:secrets/.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes[0]:
        id: bookservice-test
        uri: lb://bookservice
        predicates[0]: Path=/bookservice/book/test
        predicates[1]: Header=App-Key,AcceleratorLab
        filters:
          - name: CircuitBreaker
            args:
              name: bookCircuitBreaker
              fallbackUri: forward:/fallback/book
      routes[1]:
        id: bookservice
        uri: lb://bookservice
        predicates[0]: Path=/bookservice/book/test2
        filters:
          - name: Retry
            args:
              retries: 3
              statuses: BAD_GATEWAY
              methods: GET
          - name: CircuitBreaker
            args:
              name: bookCircuitBreaker
              fallbackUri: forward:/fallback/booktest2

      filter:
        circuit-breaker:
          enabled: true


server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${USER_SERVICE_HOST_NAME:localhost}
    instance-id: ${spring.application.name}:${random.uuid}
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
          loadbalancer:  DEBUG
    reactor:
      retry: DEBUG
