spring:
  application:
    name: myeurekaserver
    config:
      import: optional:file:secrets/.env[.properties]
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_URI:http://localhost:8761/eureka/}