spring:
  application.name: order-service
  config.import: optional:file:.env[.properties]

server:
  port: 8082

management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${ORDER_SERVICE_HOST_NAME:localhost}
    instance-id: ${spring.application.name}:${random.uuid}
