spring:
  application.name: gateway-server
  config.import: optional:file:.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: user-service
        uri: lb://user-service
        predicates[0]: Path=/api/v1/user-service/**
        predicates[1]: Header=X-Client-Type,internal
        filters:
          - AddRequestHeader=X-Gateway-Header, GatewayWasHere
          - name: CircuitBreaker
            args:
              name: userServiceCircuitBreaker
              fallbackUri: forward:/fallback/user-service
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates:
          - Path=/api/v1/order-service/**
          - Header=X-Client-Type,external
        filters:
          - name: Retry
            args:
              retries: 2
              statuses: BAD_GATEWAY
              methods: GET


management.endpoints.web.exposure.include: "*"

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${GATEWAY_HOST_NAME:localhost}
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG